# Generated by Django 5.0.3 on 2024-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoApp', '0002_alter_category_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(upload_to='assets/img/', verbose_name='Category Image'),
        ),
    ]
