# Generated by Django 5.0.3 on 2024-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=70, unique=True, verbose_name='Category')),
                ('CategoryPoints', models.IntegerField(verbose_name='Category Points')),
                ('CategoryImage', models.ImageField(upload_to='ecoApp/static/asstets/img', verbose_name='Category Image')),
                ('CategoryBrands', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
                'ordering': ['id'],
            },
        ),
    ]
