# Generated by Django 5.0.3 on 2024-05-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderdelivery_order_orderdeliveryaddress'),
        ('orderline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='order.order'),
        ),
    ]
