# Generated by Django 5.0.3 on 2024-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0002_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='OrderlineStatus',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
