# Generated by Django 5.0.3 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0003_alter_orderline_orderlinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='OrderlineStatus',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
