# Generated by Django 5.0.3 on 2024-05-14 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderPoints', models.IntegerField()),
                ('OrderStatus', models.CharField(default='Pending approval', max_length=70)),
                ('OrderHomePickup', models.BooleanField()),
                ('OrderCreationDate', models.DateField()),
                ('OrderPickupDate', models.DateField()),
                ('OrderAddress', models.CharField(blank=True, max_length=150, null=True)),
                ('OrderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
