# Generated by Django 5.0.3 on 2024-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderHomePickup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderPickupDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
