# Generated by Django 5.0.3 on 2024-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderdelivery_order_orderdeliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(choices=[('PENDING APROVAL', 'Pending aproval'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='Pending approval', max_length=70),
        ),
    ]
