# Generated by Django 5.0.3 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(choices=[('Pending aproval', 'Pending aproval'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending approval', max_length=70),
        ),
    ]
